# Generated by Django 4.2.4 on 2023-08-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrom',
            name='device',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customrom',
            name='link',
            field=models.URLField(max_length=225),
        ),
    ]
