# Generated by Django 4.2.4 on 2023-08-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customrom_device_alter_customrom_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommod',
            name='credits',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='customrom',
            name='credits',
            field=models.URLField(null=True),
        ),
    ]
