# Generated by Django 4.2.4 on 2023-08-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_bio_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='google_username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='local_username',
        ),
    ]
