# Generated by Django 4.2.4 on 2023-08-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_custommod_credits_customrom_credits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customrom',
            options={'permissions': [('can_edit_rom', 'Can edit custom ROM')]},
        ),
        migrations.AlterField(
            model_name='custommod',
            name='credits',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customrom',
            name='credits',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
