# Generated by Django 4.2.4 on 2023-08-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_popularityprediction_userinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommod',
            name='popularity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='custommod',
            name='preference',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customrom',
            name='popularity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customrom',
            name='preference',
            field=models.FloatField(null=True),
        ),
    ]
