# Generated by Django 4.2 on 2023-12-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapData',
        ),
        migrations.AddField(
            model_name='customuser',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
