# Generated by Django 4.1.2 on 2023-08-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chatmessage_delete_chatmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_direction',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], default='incoming', max_length=10),
        ),
    ]
