# Generated by Django 4.2.4 on 2023-08-12 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_customrom_options_alter_custommod_credits_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custommod',
            options={'permissions': [('can_edit_rom', 'Can edit ROM')]},
        ),
        migrations.AlterModelOptions(
            name='customrom',
            options={'permissions': [('can_edit_rom', 'Can edit ROM')]},
        ),
        migrations.AddField(
            model_name='custommod',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customrom',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
