# Generated by Django 4.2 on 2023-12-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_conversation_message_userprofile_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
