# Generated by Django 4.2.4 on 2023-08-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_custommod_options_alter_customrom_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custommod',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customrom',
            options={},
        ),
        migrations.RemoveField(
            model_name='custommod',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='customrom',
            name='uploaded_by',
        ),
    ]
