# Generated by Django 4.2.4 on 2023-08-28 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_message_chatmessage_bot_response_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
