# Generated by Django 4.2.4 on 2023-08-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_online',
        ),
    ]
