# Generated by Django 5.0 on 2024-01-08 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_message_options_remove_message_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.message'),
        ),
        migrations.RemoveField(
            model_name='messageread',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messageread',
            name='user',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='MessageRead',
        ),
    ]
