# Generated by Django 4.2.4 on 2023-08-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_usercookie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCookie',
        ),
    ]
