# Generated by Django 5.0 on 2024-02-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
