# Generated by Django 4.2.4 on 2023-09-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_custommod_image_alter_customrom_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('article_id', models.CharField(max_length=255)),
                ('article_title', models.CharField(max_length=255)),
                ('article_content', models.TextField()),
            ],
        ),
    ]
