# Generated by Django 5.0 on 2024-02-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
