# Generated by Django 5.0 on 2024-03-11 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.comment')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_comments', to='main.custommod')),
            ],
        ),
        migrations.CreateModel(
            name='RomComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.comment')),
                ('rom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rom_comments', to='main.customrom')),
            ],
        ),
    ]
