# Generated by Django 5.0 on 2024-03-12 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customrom_upload_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrom',
            name='boot_link',
        ),
        migrations.CreateModel(
            name='MODLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.custommod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='custommod',
            name='likes',
            field=models.ManyToManyField(related_name='liked_mods', to='main.modlike'),
        ),
        migrations.CreateModel(
            name='ROMLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customrom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='customrom',
            name='likes',
            field=models.ManyToManyField(related_name='liked_roms', to='main.romlike'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
