# Generated by Django 5.0 on 2024-03-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_custommod_uploaded_by_customrom_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('written_by', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('link', models.URLField()),
            ],
        ),
    ]
