# Generated by Django 5.0 on 2024-03-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='written_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
