# Generated by Django 5.0 on 2024-03-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_blog_link_alter_blog_written_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommod',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customrom',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True, unique=True),
        ),
    ]
