# Generated by Django 5.0 on 2024-03-15 13:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_custommod_slug_customrom_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommod',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='customrom',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from='name'),
        ),
    ]
