# Generated by Django 5.0 on 2024-03-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_custommod_slug_alter_customrom_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommod',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customrom',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True, unique=True),
        ),
    ]
